astarte-platform/astarte_flow

README.md
s/Astarte Streams/Astarte Flow/g .
=> README.md: Change title to Astarte Flow

lib/astarte_streams/blocks/container.ex, lib/astarte_streams/blocks/container/amqp_client.ex, lib/astarte_streams/blocks/container/rabbitmq_client.ex
The container is not yet created but the block already publishes and consumes
from AMQP
=> Add Container block

lib/astarte_flow/blocks/lua_mapper.ex, lib/astarte_flow/pipeline_builder.ex
Add config option to LuaMapper so there will no need to hardcode
configuration.
=> LuaMapper: add config

lib/astarte_flow/blocks/container.ex, lib/astarte_flow/flows/flow.ex, lib/astarte_flow/k8s.ex
Pass it to K8s when creating the CR
=> Make Flow config available to Container blocks Custom Resource

lib/astarte_flow_web/controllers/health_controller.ex
This just returns 200 if the application is able to respond for now
=> Add /health endpoint

lib/astarte_flow/flows/flow.ex
If the flow has no containers, don't install the CR and just connect the blocks
=> flow: initialize Flow CR on K8s only if needed

lib/astarte_flow/flows/flow.ex
s/container_pids/container_block_pids
=> flow: fixup K8s check modification

config/prod.exs
=> config: don't check origin in prod

lib/astarte_flow/blocks/device_events_producer/events_decoder.ex, test/blocks/device_events_producer_test.exs
Make sure that nearly any kind of incoming data is supported, except for arrays.
=> Add support to object aggregated

lib/astarte_flow/flows/flow.ex, lib/astarte_flow/pipelines.ex, lib/astarte_flow/pipelines/pipeline.ex, lib/astarte_flow_web/controllers/pipeline_controller.ex, lib/astarte_flow_web/views/pipeline_view.ex, test/astarte_streams/pipelines_test.exs, test/astarte_streams_web/controllers/pipeline_controller_test.exs
=> Add API to list and show installed pipelines

lib/astarte_flow/blocks/container.ex, lib/astarte_flow/blocks/container/amqp_client.ex, lib/astarte_flow/blocks/container/rabbitmq_client.ex, lib/astarte_flow/k8s.ex, lib/astarte_flow/pipeline_builder.ex
Allow putting a container block anywhere in the pipeline
=> Container type

.tool-versions
Signed-off-by: Riccardo <riccardo.binetti@ispirata.com>
=> Add .tool-versions file

.dockerignore, Dockerfile
Signed-off-by: Riccardo <riccardo.binetti@ispirata.com>
=> Bump Elixir version in Dockerfile and add .dockerignore

lib/astarte_flow_web/controllers/health_controller.ex
=> health_controller: remove unused aliases

test/astarte_flow/flows_test.exs, test/blocks/dynamic_virtual_device_pool_test.exs, test/blocks/virtual_device_pool_test.exs
Avoid depending on :timer.sleep whenever it's possible
=> Fix flaky tests

test/astarte_flow/flows_test.exs
The registry still thinks the flow is alive until it receives the DOWN
message
=> flows_test: ensure flow is deleted before asserting

README.md
Copy & paste a minimal description from Astarte Flow website.
=> README: write short description

lib/astarte_flow/config/xandra_nodes.ex
=> xandra_nodes: use correct module name

lib/astarte_flow/blocks/container.ex, lib/astarte_flow/blocks/container/rabbitmq_client.ex, lib/astarte_flow/blocks/device_events_producer.ex, lib/astarte_flow/blocks/device_events_producer/rabbitmq_client.ex, lib/astarte_flow/config.ex, lib/astarte_flow/pipeline_builder.ex
Do not flood consumer with messages
=> Add prefetch count to AMQP channels

config/test.exs, lib/astarte_flow/application.ex, lib/astarte_flow/blocks.ex, lib/astarte_flow/blocks/block.ex, lib/astarte_flow/blocks/default_blocks.ex, lib/astarte_flow/blocks/dets_storage.ex, lib/astarte_flow/blocks/storage.ex, lib/astarte_flow_web/controllers/block_controller.ex, lib/astarte_flow_web/controllers/fallback_controller.ex, lib/astarte_flow_web/views/block_view.ex, lib/astarte_flow_web/views/error_view.ex, test/astarte_flow/blocks_test.exs, test/astarte_flow_web/controllers/block_controller_test.exs, test/support/mocks.ex
Blocks can be composed from other blocks to create reusable components
=> Allow users to install custom blocks

lib/astarte_flow_web/telemetry.ex
=> Metrics fixes

lib/astarte_flow/flows/flow.ex, lib/astarte_flow/k8s.ex
For now, each native blocks just adds a fixed amount of CPU and memory
Close #70 
=> Pass nativeBlocks and nativeBlocksResources to k8s

lib/astarte_flow_web/views/pipeline_view.ex, test/astarte_flow_web/controllers/pipeline_controller_test.exs
=> pipeline: render schema when GETting a pipeline

lib/astarte_flow/blocks/http_sink.ex, lib/astarte_flow/blocks/http_source.ex
Allow the user to force interaction with faulty SSL certificates
=> Add ignore_ssl_errors option to Http{Source,Sink}

lib/astarte_flow/blocks/block.ex, lib/astarte_flow/flows/flow.ex, lib/astarte_flow/pipeline_builder.ex
Allow users to instantiate custom blocks in their pipelines.
=> Add support to custom Blocks

lib/astarte_flow/flows/flow.ex, lib/astarte_flow/pipeline_builder.ex, lib/astarte_flow/pipeline_builder/error.ex, lib/astarte_flow_web/controllers/flow_controller.ex, lib/astarte_flow_web/views/flow_view.ex
Return error to API user instead of crashing.
=> Report errors on flow creation

guides/0111-container.md
Add documentation for container block based on http_source doc template.
=> doc: add container block documentation

.github/workflows/docs-workflow.yaml
=> docs-workflow: fix working directories to make it work

.github/workflows/docs-workflow.yaml
=> docs-workflow: add missing with

guides/0113-random_source.md, guides/0114-json_mapper.md, guides/0115-filter.md, guides/0116-http_sink.md
Add pages for
- http_sink
- random_source
- to_json
- filter
Signed-off-by: Mattia <mattia.pavinati@ispirata.com>
=> Add doc pages for pipeline blocks

guides/core_concepts/0010-defining-a-pipeline.md
Add Installing and Running a pipeline paragraphs to Defining a Pipeline
page.
=> Add Installing and Running a pipeline

lib/astarte_flow/blocks/http_source.ex
Pipeline builder passes the headers as a map while this block was expecting a
keyword list. Change the code to handle both cases.
=> http_source: handle headers passed as map

guides/blocks/0119-virtual_device_pool.md
=> doc: add virtual_device_pool block documentation

guides/core_concepts/0001-overview.md, guides/core_concepts/0004-pipelines.md
Add brief description of pipeline concept.
=> doc: add Pipelines page

guides/core_concepts/0001-overview.md, guides/core_concepts/0005-flows.md
Add brief description of flow concept.
=> doc: add Flow documentation page

guides/core_concepts/0002-flow-messages.md, guides/core_concepts/0003-blocks.md
Make sure that other documentation pages and external resources are
linked.
=> doc: add more links to existing pages

guides/core_concepts/0001-overview.md, guides/core_concepts/0006-streams.md
Add brief documentation about streams.
=> doc: add Streams documentation

guides/blocks/0120-astarte_devices_source.md
=> doc: add astarte_devices_source block documentation

guides/blocks/0112-lua_map.md
Add missing new_message initialization to object.
Signed-off-by: Mattia <mattia.pavinati@ispirata.com>
=> 0112-lua_map.md: fix example script

guides/blocks/container.md, lib/astarte_flow/blocks/container.ex, lib/astarte_flow/k8s.ex, lib/astarte_flow/pipeline_builder.ex
Allow pulling images from private registries
=> container: add image_pull_secrets property

guides/blocks/mqtt_sink.md, lib/astarte_flow/blocks/mqtt_sink.ex, priv/blocks/mqtt_sink.json
=> Add mqtt_sink block

guides/blocks/update_metadata.md, lib/astarte_flow/blocks/update_metadata.ex, priv/blocks/update_metadata.json
Allow manipulating message metadata
=> Add update_metadata block

lib/astarte_flow/blocks/update_metadata.ex
=> update_metadata: remove debug print

.github/workflows/build-workflow.yaml, .github/workflows/docs-workflow.yaml, guides/core_concepts/0010-defining-a-pipeline.md
=> guides: add a note about JSONPath expressions and double quotes

lib/astarte_flow_web/controllers/fallback_controller.ex, lib/astarte_flow_web/views/error_view.ex
=> Return pipeline not found 404 error instead of 500

mix.exs
- update links to the source of each documentation page
- update link to the homepage of the component
=> Update links for Flow in documentation pages
