astarte-platform/astarte_flow

lib/astarte_streams/message.ex
It returns {:ok, message}, not just message
=> message: fix from_map spec

lib/astarte_flow/blocks/container.ex, lib/astarte_flow/blocks/container/amqp_client.ex, lib/astarte_flow/blocks/container/rabbitmq_client.ex, lib/astarte_flow/blocks/device_events_producer.ex, lib/astarte_flow/blocks/device_events_producer/amqp_client.ex, lib/astarte_flow/blocks/device_events_producer/rabbitmq_client.ex
Container and DeviceEventsProducer blocks open a connection to RabbitMQ. This
has to be closed when the blocks terminates, since it's not linked to the
process.
=> Make sure to terminate AMQP connections when a block terminates

lib/astarte_flow/blocks/lua_mapper.ex
Lua doesn't have a simple way to split strings, but our users will likely need it. Therefore add string_utils.split.
=> LuaMapper: add string_utils

lib/astarte_flow/pipeline_builder.ex
Add missing eval to astarte_devices_source.
=> PipelineBuilder: fix missing eval

lib/astarte_flow/pipeline_builder.ex
=> pipeline_builder: eval realm and jwt when building pairing_jwt_map

lib/astarte_flow/pipeline_builder.ex
=> pipeline_builder: interfaces must be passed in a keyword list

test/blocks/device_events_producer_test.exs
Add close_connection function, avoid crashing during tests
=> device_events_producer_test: fix FakeAMQPClient

lib/astarte_flow/blocks/random_producer.ex, lib/astarte_flow/pipeline_builder.ex
Allow sleeping for a certain amount of milliseconds between the production of
two samples. Add support for this setting also in the pipeline builder.
=> random_producer: add delay_ms option

lib/astarte_flow/blocks/virtual_device_pool.ex
This was a residue of the old format of Astarte.Flow.Message (that had map type
information alongside data), it's not needed anymore
=> virtual_device_pool: remove normalize_data function

config/test.exs, lib/astarte_flow/application.ex, lib/astarte_flow/flows.ex, lib/astarte_flow/flows/dets_storage.ex, lib/astarte_flow/flows/storage.ex, lib/astarte_flow/restore_flows_task.ex, test/astarte_flow/flows_test.exs, test/astarte_flow_web/controllers/flow_controller_test.exs
Save flows to a dets table and restore them during application startup
=> Add flows persistency

lib/astarte_flow/blocks/dynamic_virtual_device_pool.ex
=> dynamic_virtual_device_pool: remove normalize_data

.github/workflows/build-workflow.yaml
=> CI: add elixir/OTP versions to cache keys and fix codecov

lib/astarte_flow/blocks/mqtt_source.ex, lib/astarte_flow/config.ex
The erlang default of 1 is too strict. Increase the default value to 10
to make it coincident to OpenSSL default.
=> Default max certificate chain length to 10

lib/astarte_flow/blocks/device_events_producer/rabbitmq_client.ex, lib/astarte_flow/pipeline_builder.ex
astarte_events was meant to be used from trigger engine, add exchange option in order to allow consuming from any other amqp exchange.
=> DeviceEventsProducer: stop using astarte_events

lib/astarte_flow/pipelines/pipeline.ex, test/astarte_flow/pipelines_test.exs, test/astarte_flow_web/controllers/pipeline_controller_test.exs
Allow the validation of the config passed to a pipeline using a JSON schema.
=> pipeline: add schema field

.github/workflows/build-workflow.yaml, mix.exs
Do not restore deps directory for different mix.lock and use elixir and
otp versions when caching _build directory
=> CI: use correct keys for caching

lib/astarte_flow/blocks/device_events_producer/rabbitmq_client.ex
=> device_events_producer: declare the exchange during RMQ client init

lib/astarte_flow_web/endpoint.ex
Allow the Dashboard to perform health requests
=> endpoint: move CORSPlug before HealthPlug and MetricsPlug

lib/astarte_flow_web/views/block_view.ex, test/astarte_flow_web/controllers/block_controller_test.exs
Allow the API users to access all block details when listing them
=> Render blocks as object in index

lib/astarte_flow/blocks/dynamic_virtual_device_pool.ex, lib/astarte_flow/blocks/virtual_device_pool.ex, lib/astarte_flow/compat.ex, mix.lock, test/compat_test.exs
Print a warning to make users adopt the new convention before removing the
compatibility layer
=> Update astarte_device, deprecating /v1 suffix in pairing_url

.github/workflows/build-workflow.yaml, lib/astarte_flow/blocks/container.ex
If the container is a producer, then outbound queues is an empty list
=> container: don't assume we have an outbound queue

lib/astarte_flow/blocks/container.ex
This is needed if the container is started as a producer
=> container: implement handle_demand callback

.github/workflows/docs-workflow.yaml
=> docs-workflow: working-directory is not needed in setup-elixir

priv/blocks/mqtt_source.json
This PR adds a JSON Schema definition file for the `mqtt_source` block and places it together with the other default blocks.
With the definition in place, the pipeline builder can now recognize and handle `mqtt_source` blocks.
=> Add mqtt_source's JSON schema to default blocks

guides/blocks/0112-lua_map.md, guides/blocks/0117-sort.md, guides/blocks/0118-json_path_map.md, guides/blocks/0119-split_map.md
Add documentation for following blocks:
* `lua_map`
* `sort`
* `json_path_map`
* `split_map`
=> doc: add documentation for additional blocks

guides/blocks/0120-mqtt_source.md
Add markdown documentation for mqtt_source block based on http_source doc
template.
=> doc: add mqtt_source block documentation

guides/blocks/astarte_devices_source.md, guides/blocks/http_source.md, guides/blocks/mqtt_source.md, guides/blocks/random_source.md, guides/core_concepts/0002-flow-messages.md
`timestamp` contains the timestamp -> `timestamp`: contains the timestamp.
=> doc: add missing ":"

lib/astarte_flow/blocks/mqtt_sink.ex
Handler is required, we don't plan to receive messages so we just use the
default Tortoise handler for now. Also add handle_info to catch confirmation
messages for QoS 1 and QoS 2 publish.
=> mqtt_sink: fix missing handler and handle_info

lib/astarte_flow/blocks/lua_mapper.ex
Use Float.round only when data is a float but expected type is integer,
otherwise no rounding is required.
=> lua_mapper: fix: Float.round fails on integer

lib/astarte_flow/blocks/modbus_tcp_source.ex
floating point numbers type is called real and not float.
=> modbus_tcp_source: fix: floating point numbers are called real

guides/blocks/mqtt_sink.md, guides/blocks/mqtt_source.md, lib/astarte_flow/blocks/mqtt_sink.ex, lib/astarte_flow/blocks/mqtt_source.ex, priv/blocks/mqtt_sink.json, priv/blocks/mqtt_source.json
Allow passing a custom CA certificate and using mutual SSL authentication when
using both mqtt_sink and mqtt_source
=> Add custom CA and mutual SSL authentication to MQTT blocks

lib/astarte_flow/blocks/default_blocks.ex
Flow wasn't recompiled when JSON schema files were changed. Don't use
Path.expand since that will make the directory relative w.r.t. the
default_blocks.ex file, while just leaving the bare path will make it relative
to the mix.exs root (which is what we want).
=> default_blocks: fix external_resource path

lib/astarte_flow/blocks/modbus_tcp_source.ex
=> modbus_tcp_source: handle all target validation failures

lib/astarte_flow/flows/flow.ex
Avoid printing an error when a flow is deleted in a deployment that is not K8s
based, even if it doesn't need to stop anything on the K8s side.
=> flow: call K8s.try_delete_flow only if there are container blocks

priv/blocks/astarte_devices_source.json
Return the block in the list of native blocks and allow validation
=> Add astarte_devices_source.json

lib/astarte_flow/k8s.ex
Starting from the Astarte Operator v24.5, the v1alpha1 api version is removed. Therefore, to guarantee flows to be instantiated, bump the api version.
=> Bump the api version of Flows to v1alpha2
